# Generated by Django 6.0.7 on 2026-07-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_peerhospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('patient', 'Patient'), ('hospital_admin', 'Hospital Admin'), ('receptionist', 'Receptionist')], max_length=20),
        ),
    ]