# Generated by Django 5.2.15 on 2026-07-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
