# Generated by Django 5.2.15 on 2026-07-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('RECORD_CREATED', 'Record Created'), ('RECORD_VIEWED', 'Record Viewed'), ('CONSENT_GRANTED', 'Consent Granted'), ('CONSENT_REVOKED', 'Consent Revoked'), ('EMERGENCY_ACCESS_GRANTED', 'Emergency Access Granted'), ('LAB_REPORT_ADDED', 'Lab Report Added')], max_length=30),
        ),
    ]
