# Generated by Django 6.0.7 on 2026-07-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auditlog_hospital_name_alter_auditlog_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='justification',
            field=models.TextField(blank=True),
        ),
    ]
