# Generated by Django 6.0.7 on 2026-07-11 03:31

from django.db import migrations, models


def populate_hospital_name(apps, schema_editor):
    """
    Before the old `hospital` FK is dropped, copy each existing
    AccessConsent row's hospital.name into the new hospital_name field.

    Without this step, every existing row defaults to hospital_name=""
    -- fine for a single row, but the moment ANY patient already has
    more than one granted consent (to different hospitals), they all
    collide on the new unique_together=(patient, hospital_name) the
    instant it's enforced, since they'd all share hospital_name="".
    This is exactly the IntegrityError this migration used to throw
    against real data.
    """
    AccessConsent = apps.get_model('access_control', 'AccessConsent')
    for consent in AccessConsent.objects.all():
        if consent.hospital_id:
            consent.hospital_name = consent.hospital.name
            consent.save(update_fields=['hospital_name'])


def noop_reverse(apps, schema_editor):
    # Nothing to reverse -- the old `hospital` FK is gone by the time
    # anyone would roll back this far, so there'd be nothing to
    # restore it from anyway.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_emergencyaccessrequest'),
        ('accounts', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessconsent',
            name='hospital_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RunPython(populate_hospital_name, noop_reverse),
        migrations.AlterUniqueTogether(
            name='accessconsent',
            unique_together={('patient', 'hospital_name')},
        ),
        migrations.RemoveField(
            model_name='accessconsent',
            name='hospital',
        ),
    ]