# Generated by Django 6.0.7 on 2026-07-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_alter_accessconsent_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessconsent',
            name='hospital_name',
            field=models.CharField(max_length=255),
        ),
    ]
